/*   
 Emit Code 
 Name: Alexander Rivera
 Date: 4/23/2024
 Grading level: E

 This program is responsible for generating MIPS assembly code by traversing an Abstract Syntax Tree (AST).
 Most of the function within the program corresponds to a specific type of AST node and generates
 appropriate MIPS assembly instructions. 
 
 These instructions include:
 - variable declarations and assigments
 - control structures (like if, while) 
 - expressions and function calls 
 
 Other program functions handle global variables, string literals.
 
 The primary function, EMIT, initializes the process by setting up the MIPS file structure and triggers the recursive 
 parsing of the AST. The program output takes care of memory mangement with MIPS. 
 
 Capabilities:
 - Dynamic label generation for unique identification within assembly instructions.
 - Assembly output is directly linked to the structure and semantics of the source code represented by the AST.
 - Extensive use of helper functions to maintain clean code
*/


#include "ast.h"
#include "emit.h"
#include <string.h>
#include <stdlib.h>

// Global counter variable to keep track of label numbers
int labelCount = 0;

// Pre: None. Depends on global labelCount var to keep track of label counts. 
// Post: Returns a pointer to a newly created unique label string. Each label is formatted as "_Lx", where 'x' is a unique number (tracked by labelCount).
char *createLabel()
{
	char hold[100];
	char *s;
	sprintf(hold, "_L%d", labelCount++);
	s = strdup(hold);
	return (s);
} // end of createLabel

// Pre: Pointer to AST and pointer to MIPS asm file
// Post: Prints out MIPS code to asm file. Parses tree with helper function
void EMIT(ASTnode *p, FILE *fp)
{
	// Checks if either pointer is null
	if (p == NULL || fp == NULL)
	{
		return;
	}

	fprintf(fp, "# MIPS CODE GENERATED BY CS370\n");
	fprintf(fp, "\n.data\n");
	EMIT_STRINGS(p, fp); //emits strings using labels
	fprintf(fp, "\n.align 2\n");
	EMIT_GLOBALS(p, fp); //emits global vars 
	fprintf(fp, "\n.text\n\n");
	fprintf(fp, ".globl main\n\n");
	EMIT_AST(p, fp); //starts parsing the tree
	return;
} // end of EMIT

// Pre: Pointer to vars that are declared in the global scope
// POST: Prints global vars to MIPS code to file
void EMIT_GLOBALS(ASTnode *p, FILE *fp)
{

	if (p == NULL){
		return;
	}

	// Checks if node is variable and if it is global.
	if (p->type == A_VARDEC && p->symbol->level == 0){
		fprintf(fp, "%s: .space %d # Global variable\n", p->name, p->symbol->mysize * WSIZE);
	}

	EMIT_GLOBALS(p->s1, fp);
	EMIT_GLOBALS(p->s2, fp);
	EMIT_GLOBALS(p->next, fp);
} // end of EMIT_GLOBALS

// Pre: Pointer to A_WRITE node and pointer to MIPS asm file
// Post: Prints string labels with corresponding values to MIPS asm file
void EMIT_STRINGS(ASTnode *p, FILE *fp)
{
	if (p == NULL){
		return;
	}

	// Checks if node is write and if name has value.
	if (p->type == A_WRITE && p->name != NULL){
		p->label = createLabel();
		fprintf(fp, "%s: .asciiz\t %s\n", p->label, p->name);
	}

	EMIT_STRINGS(p->s1, fp);
	EMIT_STRINGS(p->s2, fp);
	EMIT_STRINGS(p->next, fp);
} // end of EMIT_STRINGS

// Pre: Pointer to Abstract syntax tree
// Post: Parses AST via a switch statement for various nodes. 
void EMIT_AST(ASTnode *p, FILE *fp)
{
	if (p == NULL){
		return;
	}

	switch (p->type){
	case A_VARDEC:
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_FUNCTIONDEC:
		EMIT_FUNCTION(p, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_WRITE:
		EMIT_WRITE(p, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_COMPOUND:
		EMIT_AST(p->s2, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_READ:
		EMIT_READ(p, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_ASSIGN:
		EMIT_ASSIGN(p, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_WHILE:
		EMIT_WHILE(p, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_IF:
		EMIT_IF(p, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_EXPRSTMT:
		EMIT_EXPR(p->s1, fp);
		EMIT_AST(p->next, fp); // Next statement 
		break;
	case A_RETURN:
		EMIT_RETURN(p, fp);
		break;
	default:
		printf("Type: %d\n", p->type);
		printf("WE SHOULD NOT BE HERE\n");
		break;
	}

} // end of EMIT_AST

// Pre:
//    FILE *fp - A pointer to the file where the assembly code will be emitted. The file must be open for writing.
//    char *label - A string representing the label for the assembly instruction. If empty, no label is written.
//    char *command - A string representing the assembly command. It should not be empty as it is the primary content.
//    char *comment - A string representing a comment to be appended to the assembly instruction. If empty, no comment is written.
// Post: Prints instructions to MIPS asm file in a format that corresponds input. 
void emit(FILE *fp, char *label, char *command, char *comment)
{
	if (strcmp("", comment) == 0)
	{
		if (strcmp("", label) == 0){
			fprintf(fp, "\t%s\t\t\n", command);
		} else {
			fprintf(fp, "%s:\t%s\t\t\n", label, command);
		}
	} else {
		if (strcmp("", label) == 0){
			fprintf(fp, "\t%s\t\t# %s\n", command, comment);
		} else {
			fprintf(fp, "%s:\t%s\t\t# %s\n", label, command, comment);
		}
	}
} // end of emit

// Pre: Pointer to A_WRITE node and pointer to MIPS asm file
// Post: Prints instructions to MIPS asm file depending of if node has a name or not. 
void EMIT_WRITE(ASTnode *p, FILE *fp)
{

	char s[100];

	// Checks if writing string or expression
	if (p->name != NULL){
		sprintf(s, "la $a0, %s", p->label);
		emit(fp, "", s, "String address");
		emit(fp, "", "li  $v0, 4", "About to print a string");
		emit(fp, "", "syscall", "call write string");
		fprintf(fp, "\n\n");
	} else {
		EMIT_EXPR(p->s1, fp);
		emit(fp, "", "li $v0, 1", "About to print a number");
		emit(fp, "", "syscall", "call write number");
		fprintf(fp, "\n\n");
	}
} // end of EMIT_WRITE

// Pre: Pointer to A_EXPR/A_NUM/A_VAR/A_CAll node and pointer to MIPS asm file 
// Post: 
// 	Prints instructions to MIPS asm file depending on node type. Does case
// 	for initial type, then does additional case analysis if type is A_EXPR
void EMIT_EXPR(ASTnode *p, FILE *fp)
{
	char s[100];

	switch (p->type){
	case A_NUM:
		sprintf(s, "li $a0, %d", p->value);
		emit(fp, "", s, "expr is constant");
		break;

	case A_EXPR:

		EMIT_EXPR(p->s1, fp);
		sprintf(s, "sw $a0, %d($sp)", p->symbol->offset * WSIZE);
		emit(fp, "", s, "expression store LHS temporarily");
		EMIT_EXPR(p->s2, fp);
		emit(fp, "", "move $a1, $a0", "right hand side needs to be a1");
		sprintf(s, "lw $a0, %d($sp)", p->symbol->offset * WSIZE);
		emit(fp, "", s, "expression restore LHS from memory");

		switch (p->operator)
		{
		case A_PLUS:
			emit(fp, "", "add $a0, $a0, $a1", "EXPR ADD");
			break;
		case A_MINUS:
			emit(fp, "", "sub $a0, $a0, $a1", "EXPR SUB");
			break;
		case A_TIMES:
			emit(fp, "", "mult $a0 $a1", "EXPR MULT");
			emit(fp, "", "mflo $a0", "EXPR MULT");
			break;
		case A_DIVIDE:
			emit(fp, "", "div $a0 $a1", "EXPR DIV");
			emit(fp, "", "mflo $a0", "EXPR DIV");
			break;
		case A_LT:
			p->label = createLabel();
			emit(fp, "", "slt $a0, $a0, $a1", "EXPR LESS THAN");
			sprintf(s, "beq $a0, $0, %s", p->label);
			emit(fp, "", s, "branch out");
			break;
		case A_LE:
			p->label = createLabel();
			emit(fp, "", "add $a1, $a1, 1", "EXPR LE add one to do compare");
			emit(fp, "", "slt $a0, $a0, $a1", "EXPR LE");
			sprintf(s, "beq $a0, $0, %s", p->label);
			emit(fp, "", s, "branch out");
			break;
		case A_GT:
			p->label = createLabel();
			emit(fp, "", "slt $a0, $a1, $a0", "EXPR Greaterthan");
			sprintf(s, "beq $a0, $0, %s", p->label);
			emit(fp, "", s, "branch out");
			break;
		case A_GE:
			p->label = createLabel();
			emit(fp, "", "add $a0, $a0, 1", "EXPR  ADD GE");
			emit(fp, "", "slt $a0, $a1, $a0", "EXPR Greaterthan");
			sprintf(s, "beq $a0, $0, %s", p->label);
			emit(fp, "", s, "branch out");
			break;
		case A_EQ:
			p->label = createLabel();
			emit(fp, "", "slt $t2 ,$a0, $a1", "EXPR EQUAL");
			emit(fp, "", "slt $t3 ,$a1, $a0", "EXPR EQUAL");
			emit(fp, "", "nor $a0 ,$t2, $t3", "EXPR EQUAL");
			emit(fp, "", "andi $a0, 1", "EXPR EQUAL");
			sprintf(s, "beq $a0, $0, %s", p->label);
			emit(fp, "", s, "branch out");
			break;
		case A_NE:
			p->label = createLabel();
			emit(fp, "", "slt $t2 ,$a0, $a1", "EXPR NEQUAL");
			emit(fp, "", "slt $t3 ,$a1, $a0", "EXPR NEQUAL");
			emit(fp, "", "or $a0 ,$t2, $t3", "EXPR NEQUAL");
			sprintf(s, "beq $a0, $0, %s", p->label);
			emit(fp, "", s, "branch out");
			break;
		case A_MODULO:
			emit(fp, "", "div $a0 $a1", "EXPR DIV remainder");
			emit(fp, "", "mfhi $a0", "EXPR DIV remainder");
			break;
		default:
			printf("Case not accounted for: %d: ", p->operator);
			break;
		}
		break;

	case A_VAR:
		EMIT_VAR(p, fp);
		emit(fp, "", "lw $a0, ($a0)", "expression is a var");
		break;
	case A_CALL:
		EMIT_CALL(p, fp);
		break;
	default:
		printf("EMIT_EXPR should never be here\n FIX!");
		printf("Case not accounted for: %d\n", p->type);
	}

} // end of EMIT_EXPR

// Pre: Pointer to A_READ node and pointer to MIPS asm file 
// Post: Mips code to read in a value and place it in the VAR of READ
void EMIT_READ(ASTnode *p, FILE *fp)
{
	// loads var in memory
	EMIT_VAR(p->s1, fp);
	emit(fp, "", "li $v0, 5", "About to read it value");
	emit(fp, "", "syscall", "read in a value $v0 now has the read val");
	emit(fp, "", "sw $v0, ($a0)", "store read in value to memory");
	fprintf(fp, "\n\n");
} // end of EMIT_READ

// Pre: Pointer to A_VAR node and pointer to MIPS asm file 
// Post: Prints instructions to MIPS asm file depending on node scope as well as the subtype (if array)
void EMIT_VAR(ASTnode *p, FILE *fp)
{
	char s[100];

	// Checking for global var
	if (p->symbol->level == 0){
		// Get the direct address of global var
		if (p->symbol->SubType == SYM_ARRAY){
			EMIT_EXPR(p->s1, fp);
		
			p->label = createLabel();

			emit(fp, "", "move $a1, $a0", "var copy index array in a1");

			emit(fp, "", "add $a0, $a0, 1", "");
			sprintf(s, "li $t1, %d", p->symbol->mysize);
			emit(fp, "", s, "");
			emit(fp, "", "slt $t0, $t1, $a0", "");
			sprintf(s, "beq $t0, $0, %s", p->label);
			emit(fp, "", s, "");

			emit(fp, "", "li $v0, 10", "");
			emit(fp, "", "syscall", "");

			fprintf(fp, "\n");
			emit(fp, p->label, "", "");

			sprintf(s, "sll $a1, $a1 %d", LOG_WSIZE);
			emit(fp, "", s, "multiply index by wordsize via SLL");

		}

		// loading var name since its global and we could just use name.
		sprintf(s, "la $a0, %s", p->name);
		emit(fp, "", s, "emit global var");
	} else {
		// local var (Stack pointer + offset)
		if (p->symbol->SubType == SYM_ARRAY){
			EMIT_EXPR(p->s1, fp);

			p->label = createLabel();

			emit(fp, "", "move $a1, $a0", "var copy index array in a1");

			emit(fp, "", "add $a0, $a0, 1", "");
			sprintf(s, "li $t1, %d", p->symbol->mysize);
			emit(fp, "", s, "");
			emit(fp, "", "slt $t0, $t1, $a0", "");
			sprintf(s, "beq $t0, $0, %s", p->label);
			emit(fp, "", s, "");

			emit(fp, "", "li $v0, 10", "");
			emit(fp, "", "syscall", "");

			fprintf(fp, "\n");
			emit(fp, p->label, "", "");

			emit(fp, "", "move $a1, $a0", "var copy index array in a1");
			sprintf(s, "sll $a1, $a1 %d", LOG_WSIZE);
			emit(fp, "", s, "multiply index by wordsize via SLL");
		}

		// loading var into memory
		emit(fp, "", "move $a0, $sp", "makes a copy of stack pointer and places in $a0");
		sprintf(s, "addi $a0, $a0, %d", p->symbol->offset * WSIZE);
		emit(fp, "", s, "stack pointer + offset");
	}

	// add on arr index if needed.
	if (p->symbol->SubType == SYM_ARRAY){
		emit(fp, "", "add $a0, $a0, $a1", "var array add internal offset");
	}

} // end of EMIT_VAR

// Pre: Pointer to A_FUNCTIONDEC node and pointer to MIPS asm file 
// Post: 
//	Prints instructions to MIPS asm file for function structure (including params). Includes 
//	implicit return depending on function name
void EMIT_FUNCTION(ASTnode *p, FILE *fp)
{
	char s[100];

	emit(fp, p->name, "", "function definition");
	emit(fp, "", "move $a1, $sp", "Activation Record carve out copy SP");
	sprintf(s, "subi $a1, $a1, %d", p->symbol->offset * WSIZE);
	emit(fp, "", s, "Activation Record carve out of function");
	emit(fp, "", "sw $ra, ($a1)", "Store return address");
	sprintf(s, "sw $sp %d($a1)", WSIZE);
	emit(fp, "", s, "Store old stack pointer");
	emit(fp, "", "move $sp, $a1", "Make SP the current activation record");
	fprintf(fp, "\n\n");

	// Copy the paramters to the formal from regster $t0 s1 linked
	ASTnode *Args = p->symbol->fparms;

	// Function counter 
	int counter = 0;

	while (Args != NULL){
		sprintf(s, "sw $t%d, %d($sp)", counter++, Args->symbol->offset * WSIZE);
		emit(fp, "", s, "Paramater store start of function");
		Args = Args->next;
	}

	fprintf(fp, "\n");

	// generate the compound statement
	EMIT_AST(p->s2, fp);

	// Restore ra and sp before we return
	emit(fp, "", "lw $ra ($sp)", "Restore old env RA");
	sprintf(s, "lw $sp, %d($sp)", WSIZE);
	emit(fp, "", s, "return from function restore sp");
	fprintf(fp, "\n");

	// Implicit return at the end of main
	if (strcmp(p->name, "main") == 0){
		// exit the system
		emit(fp, "", "li $v0, 10", "Exit from main, we are done.");
		emit(fp, "", "syscall", "Exit everything");
	} else {
		// jump back to the caller
		emit(fp, "", "jr $ra", "return to the caller");
		fprintf(fp, "\n");
	}
} // end of EMIT_FUNCTION

// Pre: Pointer to A_ASSIGN node and pointer to MIPS asm file
// Post: Prints instructions to MIPS asm file for var assingments. 
void EMIT_ASSIGN(ASTnode *p, FILE *fp)
{
	char s[100];

	// Emits the expression of assign
	EMIT_EXPR(p->s2, fp);
	sprintf(s, "sw $a0, %d($sp)", p->symbol->offset * WSIZE);
	emit(fp, "", s, "Store the old Stack pointer");

	EMIT_VAR(p->s1, fp);

	// Stores value into $a1
	sprintf(s, "lw $a1, %d($sp)", p->symbol->offset * WSIZE);
	emit(fp, "", s, "Assign get RHS temporarily");
	emit(fp, "", "sw $a1 ($a0)", "Assign place RHS into memory");

} // end of EMIT_ASSIGN

// Pre: Pointer to A_WHILE node and pointer to MIPS asm file
// Post: 
// 	Prints instructions to MIPS asm file for while statements and emits asm code corresponding
// 	to a while loop structure 
void EMIT_WHILE(ASTnode *p, FILE *fp)
{
	char s[100];

	// create both labels here
	p->label = createLabel();
	sprintf(s, "\n%s", p->label);
	emit(fp, s, "", "");

	// emit the expression and do comparisons
	EMIT_EXPR(p->s1, fp);
	EMIT_AST(p->s2, fp);

	sprintf(s, "j %s", p->label);
	emit(fp, "", s, "WHILE Jump back");

	emit(fp, p->s1->label, "", "");

} // end of EMIT_WHILE

// Pre: Pointer to A_CALL node and pointer to MIPS asm file
// Post: Prints instructions to MIPS asm file for function calls. Checks for args in function call. 
void EMIT_CALL(ASTnode *p, FILE *fp)
{
	char s[100];
	int counter = 0;

	fprintf(fp,"\n");

	// Checks of there are arguments 
	if (p->s1 != NULL){
		if (p->s1->s1 != NULL){
			EMIT_EXPR(p->s1->s1, fp);

			sprintf(s, "sw $a0, %d($sp)", p->s1->symbol->offset * WSIZE);
			emit(fp, "", s, "move arg in temp");

			sprintf(s, "lw $a0, %d($sp)", p->s1->symbol->offset * WSIZE);
			emit(fp, "", s, "pull out stored  Arg");

			emit(fp, "", "move $t0, $a0", "move arg in temp");
		}
	}

	sprintf(s, "jal %s", p->name);

	emit(fp, "", s, "Call the function");
	fprintf(fp, "\n");

} // end of EMIT_CALL

// Pre: Pointer to A_RETURN and pointer to MIPS asm file
// Post: Prints instructions to MIPS asm file for return statements. Checks if return has value or not.
void EMIT_RETURN(ASTnode *p, FILE *fp)
{
	char s[100];

	if (p->s1 == NULL){
		emit(fp, "", "li $a0, 0", "RETURN has no specified value set to 0");
	} else {
		EMIT_EXPR(p->s1, fp);
	}

} // end of EMIT_RETURN

// Pre: Pointer to A_IF and pointer to MIPS asm file
// Post: Prints instructions to MIPS asm file for if statements. 
void EMIT_IF(ASTnode *p, FILE *fp)
{
	char s[100];

	EMIT_EXPR(p->s1->s1, fp);
	fprintf(fp, "\n");

	EMIT_AST(p->s2->s1, fp);

	p->s2->label = createLabel();

	// If s1 end
	sprintf(s, "j %s", p->s2->label);
	emit(fp, "", s, "IF S1 end");

	// Else 
	emit(fp, p->s1->s1->label, "", "ELSE target");
	emit(fp, "", "", "The negative portion of IF if ther is an else");
	emit(fp, "", "", "Otherwise just these lines");
	EMIT_AST(p->s2->s2, fp);

	emit(fp, p->s2->label, "", "End of IF");

} // end of EMIT_IF

void EMIT_TWIF(ASTnode *p, FILE *fp){


	char s[100];


}

int STRING_COUNT(ASTnode *p){

	if (p == NULL){
		return 0;
	}

	int count = 0;
	if (p->type == A_WRITE && p->name != NULL){
		count = 1;
	}

	return count + STRING_COUNT(p->s1) + STRING_COUNT(p->s2) + STRING_COUNT(p->next);
}

int GLOBAL_SPACE(ASTnode *p){

	if (p == NULL){
		return 0;
	}

	int space = 0;
	if (p->type == A_VARDEC && p->symbol->level == 0){
		space += p->symbol->mysize;
	}

	return space + GLOBAL_SPACE(p->s1) + GLOBAL_SPACE(p->s2) + GLOBAL_SPACE(p->next);
}