# MIPS CODE GENERATED BY CS370

.data
_L0: .asciiz	 "\n"
_L1: .asciiz	 "got here"

.align 2
A: .space 24 # Global variable

.text

.globl main

main:			# function definition
	move $a1, $sp		# Activation Record carve out copy SP
	subi $a1, $a1, 12		# Activation Record carve out of function
	sw $ra, ($a1)		# Store return address
	sw $sp 4($a1)		# Store old stack pointer
	move $sp, $a1		# Make SP the current activation record



	move $a0, $sp		# makes a copy of stack pointer and places in $a0
	addi $a0, $a0, 8		# stack pointer + offset
	li $v0, 5		# About to read it value
	syscall		# read in a value $v0 now has the read val
	sw $v0, ($a0)		# store read in value to memory


	la $a0, _L0		# String address
	li  $v0, 4		# About to print a string
	syscall		# call write string


	move $a0, $sp		# makes a copy of stack pointer and places in $a0
	addi $a0, $a0, 8		# stack pointer + offset
	lw $a0, ($a0)		# expression is a var
	move $a1, $a0		# var copy index array in a1
	add $a0, $a0, 1		
	li $t1, 6		
	slt $t0, $t1, $a0		
	beq $t0, $0, _L2		
	li $v0, 10		
	syscall		

_L2:			
	sll $a1, $a1 2		# multiply index by wordsize via SLL
	la $a0, A		# emit global var
	add $a0, $a0, $a1		# var array add internal offset
	lw $a0, ($a0)		# expression is a var
	li $v0, 1		# About to print a number
	syscall		# call write number


	la $a0, _L1		# String address
	li  $v0, 4		# About to print a string
	syscall		# call write string


	lw $ra ($sp)		# Restore old env RA
	lw $sp, 4($sp)		# return from function restore sp

	li $v0, 10		# Exit from main, we are done.
	syscall		# Exit everything
